### ISSUE TITLE
Transformation error (did not recognize object of type "ChainExpression")

### ISSUE THREAD

**Issue by connorjclark** [villesau/optional-chaining-codemod#48]
Seems the codemod does not support running on code that already utilizes optional chaining.

```
lighthouse-core/computed/metrics/timing-summary.js Transformation error (did not recognize object of type "ChainExpression")
Error: did not recognize object of type "ChainExpression"
    at Object.getFieldNames (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/types.js:661:19)
    at visitChildren (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path-visitor.js:186:36)
    at Visitor.PVp.visitWithoutReset (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path-visitor.js:168:20)
    at visitChildren (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path-visitor.js:205:25)
    at Visitor.PVp.visitWithoutReset (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path-visitor.js:168:20)
    at NodePath.each (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path.js:89:26)
    at visitChildren (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path-visitor.js:180:18)
    at Visitor.PVp.visitWithoutReset (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path-visitor.js:168:20)
    at visitChildren (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path-visitor.js:205:25)
    at Visitor.PVp.visitWithoutReset (/Users/cjamcl/.npm/_npx/42135/lib/node_modules/optional-chaining-codemod/node_modules/ast-types/lib/path-visitor.js:168:20)
```

I believe it was resolved here: https://github.com/benjamn/ast-types/issues/383

**Comment by villesau** [comment]
@connorjclark can you give a small snippet to reproduce? I was able to run it against `const result = a?.b?.[0].something;`

**Comment by villesau** [comment]
Updated jscodeshift, that might fix the issue.

**Comment by connorjclark** [comment]
It sure did! thanks for the quick turnaround, and for the nice tool :)

**Comment by villesau** [comment]
No worries, great to see that the tool has been useful in such a great project I use my self as well! :)
